### ISSUE TITLE
Can't find ffmpeg even though it exists

### ISSUE THREAD

**Issue by True-Protocol** [IoeCmcomc/NBSTool#10]
When exporting, I am getting this error:

![image](https://github.com/IoeCmcomc/NBSTool/assets/49531692/a58b4c8e-df99-442e-99a6-c50fe246dcd4)

even though those files do exist:

![image](https://github.com/IoeCmcomc/NBSTool/assets/49531692/48d5b57f-b063-4d8f-bf89-8bd5420567da)

I've tried running main.exe as an Administrator but no change.
I've also tried updating to the latest builds of these files and the same issue happens.

**Comment by IoeCmcomc** [comment]
What version of NBSTool and Windows are you using? You can check the NBSTool's version in the Help | About menu.

**Comment by True-Protocol** [comment]
NBSTool Version 1.3.0
Windows 10 (not sure exact version, more than likely whatever the latest is. I can check after work today)

**Comment by IoeCmcomc** [comment]
What happens if you ignore the warning and continue to export?

**Comment by True-Protocol** [comment]
It fails to export anything

**Comment by IoeCmcomc** [comment]
What is the specific error message (not the warning) when you try to export anyway? Can you take a screenshot of the error?
It's likely that the warning is false, because the code only checks for `ffmpeg` and `ffprobe` in the PATH environment variable to show the warning.

**Comment by True-Protocol** [comment]
No error. It just doesn't generate anything

**Comment by IoeCmcomc** [comment]
Have you tried adding the path of the `ffmpeg/bin` folder to the PATH environment variable?
After closing the warning, does the audio export dialog even show up?
