### ISSUE TITLE
Add import equivalents to export options

### ISSUE THREAD

**Issue by RedVortexDev** [IoeCmcomc/NBSTool#4]
So you can give it a JSON/MIDI file and it gives back an NBS/Audio

**Comment by IoeCmcomc** [comment]
MIDI file importing is planned, so I will start implementing it when I have time. JSON importing may need to be investigated, but that's a good idea.

**Comment by IoeCmcomc** [comment]
I have implemented importing from MIDI and JSON files in 56f5446 and 09139fe. The feature will be available in the next release.
If you want to try it now, you can download one of the artifacts in [this Github Action](https://github.com/IoeCmcomc/NBSTool/actions/runs/4261611576).
